// Code generated by acpgen from schema/schema.json; DO NOT EDIT.

package protocol

import "encoding/json"

func marshalDiscriminatedUnion(propertyName, propertyValue string, value any) json.RawMessage {
	data, err := json.Marshal(value)
	if err != nil {
		return nil
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil || fields == nil {
		fields = map[string]json.RawMessage{}
	}
	discriminator, err := json.Marshal(propertyValue)
	if err != nil {
		return nil
	}
	fields[propertyName] = discriminator
	data, err = json.Marshal(fields)
	if err != nil {
		return nil
	}
	return data
}

type AgentCapabilities struct {
	Meta                map[string]any      `json:"_meta,omitempty"`
	LoadSession         bool                `json:"loadSession,omitempty"`
	MCPCapabilities     MCPCapabilities     `json:"mcpCapabilities,omitempty"`
	PromptCapabilities  PromptCapabilities  `json:"promptCapabilities,omitempty"`
	SessionCapabilities SessionCapabilities `json:"sessionCapabilities,omitempty"`
}

type Annotations struct {
	Meta         map[string]any `json:"_meta,omitempty"`
	Audience     []Role         `json:"audience,omitempty"`
	LastModified *string        `json:"lastModified,omitempty"`
	Priority     *float64       `json:"priority,omitempty"`
}

type AudioContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Data        string         `json:"data"`
	MimeType    string         `json:"mimeType"`
}

type AuthMethod = AuthMethodAgent

type AuthMethodAgent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description *string        `json:"description,omitempty"`
	ID          string         `json:"id"`
	Name        string         `json:"name"`
}

const AuthenticateRequestMethod = "authenticate"

type AuthenticateRequest struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	MethodID string         `json:"methodId"`
}

const AuthenticateResponseMethod = "authenticate"

type AuthenticateResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type AvailableCommand struct {
	Meta        map[string]any         `json:"_meta,omitempty"`
	Description string                 `json:"description"`
	Input       *AvailableCommandInput `json:"input,omitempty"`
	Name        string                 `json:"name"`
}

type AvailableCommandInput = UnstructuredCommandInput

type AvailableCommandsUpdate struct {
	Meta              map[string]any     `json:"_meta,omitempty"`
	AvailableCommands []AvailableCommand `json:"availableCommands"`
}

type BlobResourceContents struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	Blob     string         `json:"blob"`
	MimeType *string        `json:"mimeType,omitempty"`
	URI      string         `json:"uri"`
}

const CancelNotificationMethod = "session/cancel"

type CancelNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
}

type ClientCapabilities struct {
	Meta     map[string]any         `json:"_meta,omitempty"`
	FS       FileSystemCapabilities `json:"fs,omitempty"`
	Terminal bool                   `json:"terminal,omitempty"`
}

const CloseSessionRequestMethod = "session/close"

type CloseSessionRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
}

const CloseSessionResponseMethod = "session/close"

type CloseSessionResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type ConfigOptionUpdate struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions"`
}

type Content struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content ContentBlock   `json:"content"`
}

type ContentBlock struct {
	data json.RawMessage
}

func NewContentBlockRaw(data json.RawMessage) ContentBlock {
	return ContentBlock{data: append(json.RawMessage(nil), data...)}
}

func (m *ContentBlock) UnmarshalJSON(data []byte) error {
	m.data = append(m.data[:0], data...)
	return nil
}

func (m ContentBlock) MarshalJSON() ([]byte, error) {
	if len(m.data) == 0 {
		return []byte("null"), nil
	}
	return m.data, nil
}

func (m ContentBlock) Raw() json.RawMessage {
	return append(json.RawMessage(nil), m.data...)
}

type ContentBlockVariant interface {
	isContentBlockVariant()
	ContentBlock() ContentBlock
}

const ContentBlockTextType = "text"

type ContentBlockText struct {
	TextContent
}

func (ContentBlockText) isContentBlockVariant() {}

func (v ContentBlockText) ContentBlock() ContentBlock {
	return ContentBlock{data: marshalDiscriminatedUnion("type", ContentBlockTextType, v)}
}

const ContentBlockImageType = "image"

type ContentBlockImage struct {
	ImageContent
}

func (ContentBlockImage) isContentBlockVariant() {}

func (v ContentBlockImage) ContentBlock() ContentBlock {
	return ContentBlock{data: marshalDiscriminatedUnion("type", ContentBlockImageType, v)}
}

const ContentBlockAudioType = "audio"

type ContentBlockAudio struct {
	AudioContent
}

func (ContentBlockAudio) isContentBlockVariant() {}

func (v ContentBlockAudio) ContentBlock() ContentBlock {
	return ContentBlock{data: marshalDiscriminatedUnion("type", ContentBlockAudioType, v)}
}

const ContentBlockResourceLinkType = "resource_link"

type ContentBlockResourceLink struct {
	ResourceLink
}

func (ContentBlockResourceLink) isContentBlockVariant() {}

func (v ContentBlockResourceLink) ContentBlock() ContentBlock {
	return ContentBlock{data: marshalDiscriminatedUnion("type", ContentBlockResourceLinkType, v)}
}

const ContentBlockResourceType = "resource"

type ContentBlockResource struct {
	EmbeddedResource
}

func (ContentBlockResource) isContentBlockVariant() {}

func (v ContentBlockResource) ContentBlock() ContentBlock {
	return ContentBlock{data: marshalDiscriminatedUnion("type", ContentBlockResourceType, v)}
}

type UnknownContentBlock struct {
	Discriminator string
	Raw           json.RawMessage
}

func (UnknownContentBlock) isContentBlockVariant() {}

func (v UnknownContentBlock) ContentBlock() ContentBlock {
	return ContentBlock{data: append(json.RawMessage(nil), v.Raw...)}
}

func (m ContentBlock) Variant() ContentBlockVariant {
	variant, err := DecodeContentBlock(m.Raw())
	if err != nil {
		return UnknownContentBlock{Raw: m.Raw()}
	}
	return variant
}

func DecodeContentBlock(data json.RawMessage) (ContentBlockVariant, error) {
	var header struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, err
	}
	switch header.Type {
	case ContentBlockTextType:
		var value ContentBlockText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case ContentBlockImageType:
		var value ContentBlockImage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case ContentBlockAudioType:
		var value ContentBlockAudio
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case ContentBlockResourceLinkType:
		var value ContentBlockResourceLink
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case ContentBlockResourceType:
		var value ContentBlockResource
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	default:
		return UnknownContentBlock{Discriminator: header.Type, Raw: append(json.RawMessage(nil), data...)}, nil
	}
}

type ContentChunk struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content ContentBlock   `json:"content"`
}

const CreateTerminalRequestMethod = "terminal/create"

type CreateTerminalRequest struct {
	Meta            map[string]any `json:"_meta,omitempty"`
	Args            []string       `json:"args,omitempty"`
	Command         string         `json:"command"`
	Cwd             *string        `json:"cwd,omitempty"`
	Env             []EnvVariable  `json:"env,omitempty"`
	OutputByteLimit *uint64        `json:"outputByteLimit,omitempty"`
	SessionID       SessionID      `json:"sessionId"`
}

const CreateTerminalResponseMethod = "terminal/create"

type CreateTerminalResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	TerminalID string         `json:"terminalId"`
}

type CurrentModeUpdate struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	CurrentModeID SessionModeID  `json:"currentModeId"`
}

type Diff struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	NewText string         `json:"newText"`
	OldText *string        `json:"oldText,omitempty"`
	Path    string         `json:"path"`
}

type EmbeddedResource struct {
	Meta        map[string]any           `json:"_meta,omitempty"`
	Annotations *Annotations             `json:"annotations,omitempty"`
	Resource    EmbeddedResourceResource `json:"resource"`
}

type EmbeddedResourceResource = json.RawMessage

type EnvVariable struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Name  string         `json:"name"`
	Value string         `json:"value"`
}

type FileSystemCapabilities struct {
	Meta          map[string]any `json:"_meta,omitempty"`
	ReadTextFile  bool           `json:"readTextFile,omitempty"`
	WriteTextFile bool           `json:"writeTextFile,omitempty"`
}

type HttpHeader struct {
	Meta  map[string]any `json:"_meta,omitempty"`
	Name  string         `json:"name"`
	Value string         `json:"value"`
}

type ImageContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Data        string         `json:"data"`
	MimeType    string         `json:"mimeType"`
	URI         *string        `json:"uri,omitempty"`
}

type Implementation struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Name    string         `json:"name"`
	Title   *string        `json:"title,omitempty"`
	Version string         `json:"version"`
}

const InitializeRequestMethod = "initialize"

type InitializeRequest struct {
	Meta               map[string]any     `json:"_meta,omitempty"`
	ClientCapabilities ClientCapabilities `json:"clientCapabilities,omitempty"`
	ClientInfo         *Implementation    `json:"clientInfo,omitempty"`
	ProtocolVersion    ProtocolVersion    `json:"protocolVersion"`
}

const InitializeResponseMethod = "initialize"

type InitializeResponse struct {
	Meta              map[string]any    `json:"_meta,omitempty"`
	AgentCapabilities AgentCapabilities `json:"agentCapabilities,omitempty"`
	AgentInfo         *Implementation   `json:"agentInfo,omitempty"`
	AuthMethods       []AuthMethod      `json:"authMethods,omitempty"`
	ProtocolVersion   ProtocolVersion   `json:"protocolVersion"`
}

const KillTerminalRequestMethod = "terminal/kill"

type KillTerminalRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

const KillTerminalResponseMethod = "terminal/kill"

type KillTerminalResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

const ListSessionsRequestMethod = "session/list"

type ListSessionsRequest struct {
	Meta   map[string]any `json:"_meta,omitempty"`
	Cursor *string        `json:"cursor,omitempty"`
	Cwd    *string        `json:"cwd,omitempty"`
}

const ListSessionsResponseMethod = "session/list"

type ListSessionsResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	NextCursor *string        `json:"nextCursor,omitempty"`
	Sessions   []SessionInfo  `json:"sessions"`
}

const LoadSessionRequestMethod = "session/load"

type LoadSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers"`
	SessionID  SessionID      `json:"sessionId"`
}

const LoadSessionResponseMethod = "session/load"

type LoadSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
}

type MCPCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
	HTTP bool           `json:"http,omitempty"`
	SSE  bool           `json:"sse,omitempty"`
}

type MCPServer json.RawMessage

type MCPServerHttp struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Headers []HttpHeader   `json:"headers"`
	Name    string         `json:"name"`
	URL     string         `json:"url"`
}

type MCPServerSse struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Headers []HttpHeader   `json:"headers"`
	Name    string         `json:"name"`
	URL     string         `json:"url"`
}

type MCPServerStdio struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Args    []string       `json:"args"`
	Command string         `json:"command"`
	Env     []EnvVariable  `json:"env"`
	Name    string         `json:"name"`
}

const NewSessionRequestMethod = "session/new"

type NewSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers"`
}

const NewSessionResponseMethod = "session/new"

type NewSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
	SessionID     SessionID             `json:"sessionId"`
}

type PermissionOption struct {
	Meta     map[string]any       `json:"_meta,omitempty"`
	Kind     PermissionOptionKind `json:"kind"`
	Name     string               `json:"name"`
	OptionID PermissionOptionID   `json:"optionId"`
}

type PermissionOptionID string

type PermissionOptionKind string

const (
	PermissionOptionKindAllowOnce    PermissionOptionKind = "allow_once"
	PermissionOptionKindAllowAlways  PermissionOptionKind = "allow_always"
	PermissionOptionKindRejectOnce   PermissionOptionKind = "reject_once"
	PermissionOptionKindRejectAlways PermissionOptionKind = "reject_always"
)

type Plan struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Entries []PlanEntry    `json:"entries"`
}

type PlanEntry struct {
	Meta     map[string]any    `json:"_meta,omitempty"`
	Content  string            `json:"content"`
	Priority PlanEntryPriority `json:"priority"`
	Status   PlanEntryStatus   `json:"status"`
}

type PlanEntryPriority string

const (
	PlanEntryPriorityHigh   PlanEntryPriority = "high"
	PlanEntryPriorityMedium PlanEntryPriority = "medium"
	PlanEntryPriorityLow    PlanEntryPriority = "low"
)

type PlanEntryStatus string

const (
	PlanEntryStatusPending    PlanEntryStatus = "pending"
	PlanEntryStatusInProgress PlanEntryStatus = "in_progress"
	PlanEntryStatusCompleted  PlanEntryStatus = "completed"
)

type PromptCapabilities struct {
	Meta            map[string]any `json:"_meta,omitempty"`
	Audio           bool           `json:"audio,omitempty"`
	EmbeddedContext bool           `json:"embeddedContext,omitempty"`
	Image           bool           `json:"image,omitempty"`
}

const PromptRequestMethod = "session/prompt"

type PromptRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Prompt    []ContentBlock `json:"prompt"`
	SessionID SessionID      `json:"sessionId"`
}

const PromptResponseMethod = "session/prompt"

type PromptResponse struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	StopReason StopReason     `json:"stopReason"`
}

type ProtocolVersion uint16

const ReadTextFileRequestMethod = "fs/read_text_file"

type ReadTextFileRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Limit     *uint32        `json:"limit,omitempty"`
	Line      *uint32        `json:"line,omitempty"`
	Path      string         `json:"path"`
	SessionID SessionID      `json:"sessionId"`
}

const ReadTextFileResponseMethod = "fs/read_text_file"

type ReadTextFileResponse struct {
	Meta    map[string]any `json:"_meta,omitempty"`
	Content string         `json:"content"`
}

const ReleaseTerminalRequestMethod = "terminal/release"

type ReleaseTerminalRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

const ReleaseTerminalResponseMethod = "terminal/release"

type ReleaseTerminalResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type RequestPermissionOutcome struct {
	data json.RawMessage
}

func NewRequestPermissionOutcomeRaw(data json.RawMessage) RequestPermissionOutcome {
	return RequestPermissionOutcome{data: append(json.RawMessage(nil), data...)}
}

func (m *RequestPermissionOutcome) UnmarshalJSON(data []byte) error {
	m.data = append(m.data[:0], data...)
	return nil
}

func (m RequestPermissionOutcome) MarshalJSON() ([]byte, error) {
	if len(m.data) == 0 {
		return []byte("null"), nil
	}
	return m.data, nil
}

func (m RequestPermissionOutcome) Raw() json.RawMessage {
	return append(json.RawMessage(nil), m.data...)
}

type RequestPermissionOutcomeVariant interface {
	isRequestPermissionOutcomeVariant()
	RequestPermissionOutcome() RequestPermissionOutcome
}

const RequestPermissionOutcomeCancelledOutcome = "cancelled"

type RequestPermissionOutcomeCancelled struct {
}

func (RequestPermissionOutcomeCancelled) isRequestPermissionOutcomeVariant() {}

func (v RequestPermissionOutcomeCancelled) RequestPermissionOutcome() RequestPermissionOutcome {
	return RequestPermissionOutcome{data: marshalDiscriminatedUnion("outcome", RequestPermissionOutcomeCancelledOutcome, v)}
}

const RequestPermissionOutcomeSelectedOutcome = "selected"

type RequestPermissionOutcomeSelected struct {
	SelectedPermissionOutcome
}

func (RequestPermissionOutcomeSelected) isRequestPermissionOutcomeVariant() {}

func (v RequestPermissionOutcomeSelected) RequestPermissionOutcome() RequestPermissionOutcome {
	return RequestPermissionOutcome{data: marshalDiscriminatedUnion("outcome", RequestPermissionOutcomeSelectedOutcome, v)}
}

type UnknownRequestPermissionOutcome struct {
	Discriminator string
	Raw           json.RawMessage
}

func (UnknownRequestPermissionOutcome) isRequestPermissionOutcomeVariant() {}

func (v UnknownRequestPermissionOutcome) RequestPermissionOutcome() RequestPermissionOutcome {
	return RequestPermissionOutcome{data: append(json.RawMessage(nil), v.Raw...)}
}

func (m RequestPermissionOutcome) Variant() RequestPermissionOutcomeVariant {
	variant, err := DecodeRequestPermissionOutcome(m.Raw())
	if err != nil {
		return UnknownRequestPermissionOutcome{Raw: m.Raw()}
	}
	return variant
}

func DecodeRequestPermissionOutcome(data json.RawMessage) (RequestPermissionOutcomeVariant, error) {
	var header struct {
		Outcome string `json:"outcome"`
	}
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, err
	}
	switch header.Outcome {
	case RequestPermissionOutcomeCancelledOutcome:
		var value RequestPermissionOutcomeCancelled
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case RequestPermissionOutcomeSelectedOutcome:
		var value RequestPermissionOutcomeSelected
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	default:
		return UnknownRequestPermissionOutcome{Discriminator: header.Outcome, Raw: append(json.RawMessage(nil), data...)}, nil
	}
}

const RequestPermissionRequestMethod = "session/request_permission"

type RequestPermissionRequest struct {
	Meta      map[string]any     `json:"_meta,omitempty"`
	Options   []PermissionOption `json:"options"`
	SessionID SessionID          `json:"sessionId"`
	ToolCall  ToolCallUpdate     `json:"toolCall"`
}

const RequestPermissionResponseMethod = "session/request_permission"

type RequestPermissionResponse struct {
	Meta    map[string]any           `json:"_meta,omitempty"`
	Outcome RequestPermissionOutcome `json:"outcome"`
}

type ResourceLink struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Description *string        `json:"description,omitempty"`
	MimeType    *string        `json:"mimeType,omitempty"`
	Name        string         `json:"name"`
	Size        *int64         `json:"size,omitempty"`
	Title       *string        `json:"title,omitempty"`
	URI         string         `json:"uri"`
}

const ResumeSessionRequestMethod = "session/resume"

type ResumeSessionRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	Cwd        string         `json:"cwd"`
	MCPServers []MCPServer    `json:"mcpServers,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
}

const ResumeSessionResponseMethod = "session/resume"

type ResumeSessionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions,omitempty"`
	Modes         *SessionModeState     `json:"modes,omitempty"`
}

type Role string

const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

type SelectedPermissionOutcome struct {
	Meta     map[string]any     `json:"_meta,omitempty"`
	OptionID PermissionOptionID `json:"optionId"`
}

type SessionCapabilities struct {
	Meta   map[string]any             `json:"_meta,omitempty"`
	Close  *SessionCloseCapabilities  `json:"close,omitempty"`
	List   *SessionListCapabilities   `json:"list,omitempty"`
	Resume *SessionResumeCapabilities `json:"resume,omitempty"`
}

type SessionCloseCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type SessionConfigGroupID string

type SessionConfigID string

type SessionConfigOption struct {
	data json.RawMessage
}

func NewSessionConfigOptionRaw(data json.RawMessage) SessionConfigOption {
	return SessionConfigOption{data: append(json.RawMessage(nil), data...)}
}

func (m *SessionConfigOption) UnmarshalJSON(data []byte) error {
	m.data = append(m.data[:0], data...)
	return nil
}

func (m SessionConfigOption) MarshalJSON() ([]byte, error) {
	if len(m.data) == 0 {
		return []byte("null"), nil
	}
	return m.data, nil
}

func (m SessionConfigOption) Raw() json.RawMessage {
	return append(json.RawMessage(nil), m.data...)
}

type SessionConfigOptionVariant interface {
	isSessionConfigOptionVariant()
	SessionConfigOption() SessionConfigOption
}

const SessionConfigOptionSelectType = "select"

type SessionConfigOptionSelect struct {
	SessionConfigSelect
}

func (SessionConfigOptionSelect) isSessionConfigOptionVariant() {}

func (v SessionConfigOptionSelect) SessionConfigOption() SessionConfigOption {
	return SessionConfigOption{data: marshalDiscriminatedUnion("type", SessionConfigOptionSelectType, v)}
}

type UnknownSessionConfigOption struct {
	Discriminator string
	Raw           json.RawMessage
}

func (UnknownSessionConfigOption) isSessionConfigOptionVariant() {}

func (v UnknownSessionConfigOption) SessionConfigOption() SessionConfigOption {
	return SessionConfigOption{data: append(json.RawMessage(nil), v.Raw...)}
}

func (m SessionConfigOption) Variant() SessionConfigOptionVariant {
	variant, err := DecodeSessionConfigOption(m.Raw())
	if err != nil {
		return UnknownSessionConfigOption{Raw: m.Raw()}
	}
	return variant
}

func DecodeSessionConfigOption(data json.RawMessage) (SessionConfigOptionVariant, error) {
	var header struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, err
	}
	switch header.Type {
	case SessionConfigOptionSelectType:
		var value SessionConfigOptionSelect
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	default:
		return UnknownSessionConfigOption{Discriminator: header.Type, Raw: append(json.RawMessage(nil), data...)}, nil
	}
}

type SessionConfigOptionCategory string

const (
	SessionConfigOptionCategoryMode         SessionConfigOptionCategory = "mode"
	SessionConfigOptionCategoryModel        SessionConfigOptionCategory = "model"
	SessionConfigOptionCategoryThoughtLevel SessionConfigOptionCategory = "thought_level"
)

type SessionConfigSelect struct {
	CurrentValue SessionConfigValueID       `json:"currentValue"`
	Options      SessionConfigSelectOptions `json:"options"`
}

type SessionConfigSelectGroup struct {
	Meta    map[string]any              `json:"_meta,omitempty"`
	Group   SessionConfigGroupID        `json:"group"`
	Name    string                      `json:"name"`
	Options []SessionConfigSelectOption `json:"options"`
}

type SessionConfigSelectOption struct {
	Meta        map[string]any       `json:"_meta,omitempty"`
	Description *string              `json:"description,omitempty"`
	Name        string               `json:"name"`
	Value       SessionConfigValueID `json:"value"`
}

type SessionConfigSelectOptions = json.RawMessage

type SessionConfigValueID string

type SessionID string

type SessionInfo struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Cwd       string         `json:"cwd"`
	SessionID SessionID      `json:"sessionId"`
	Title     *string        `json:"title,omitempty"`
	UpdatedAt *string        `json:"updatedAt,omitempty"`
}

type SessionInfoUpdate struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Title     *string        `json:"title,omitempty"`
	UpdatedAt *string        `json:"updatedAt,omitempty"`
}

type SessionListCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type SessionMode struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Description *string        `json:"description,omitempty"`
	ID          SessionModeID  `json:"id"`
	Name        string         `json:"name"`
}

type SessionModeID string

type SessionModeState struct {
	Meta           map[string]any `json:"_meta,omitempty"`
	AvailableModes []SessionMode  `json:"availableModes"`
	CurrentModeID  SessionModeID  `json:"currentModeId"`
}

const SessionNotificationMethod = "session/update"

type SessionNotification struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	SessionID SessionID      `json:"sessionId"`
	Update    SessionUpdate  `json:"update"`
}

type SessionResumeCapabilities struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type SessionUpdate struct {
	data json.RawMessage
}

func NewSessionUpdateRaw(data json.RawMessage) SessionUpdate {
	return SessionUpdate{data: append(json.RawMessage(nil), data...)}
}

func (m *SessionUpdate) UnmarshalJSON(data []byte) error {
	m.data = append(m.data[:0], data...)
	return nil
}

func (m SessionUpdate) MarshalJSON() ([]byte, error) {
	if len(m.data) == 0 {
		return []byte("null"), nil
	}
	return m.data, nil
}

func (m SessionUpdate) Raw() json.RawMessage {
	return append(json.RawMessage(nil), m.data...)
}

type SessionUpdateVariant interface {
	isSessionUpdateVariant()
	SessionUpdate() SessionUpdate
}

const SessionUpdateUserMessageChunkSessionUpdate = "user_message_chunk"

type SessionUpdateUserMessageChunk struct {
	ContentChunk
}

func (SessionUpdateUserMessageChunk) isSessionUpdateVariant() {}

func (v SessionUpdateUserMessageChunk) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateUserMessageChunkSessionUpdate, v)}
}

const SessionUpdateAgentMessageChunkSessionUpdate = "agent_message_chunk"

type SessionUpdateAgentMessageChunk struct {
	ContentChunk
}

func (SessionUpdateAgentMessageChunk) isSessionUpdateVariant() {}

func (v SessionUpdateAgentMessageChunk) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateAgentMessageChunkSessionUpdate, v)}
}

const SessionUpdateAgentThoughtChunkSessionUpdate = "agent_thought_chunk"

type SessionUpdateAgentThoughtChunk struct {
	ContentChunk
}

func (SessionUpdateAgentThoughtChunk) isSessionUpdateVariant() {}

func (v SessionUpdateAgentThoughtChunk) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateAgentThoughtChunkSessionUpdate, v)}
}

const SessionUpdateToolCallSessionUpdate = "tool_call"

type SessionUpdateToolCall struct {
	ToolCall
}

func (SessionUpdateToolCall) isSessionUpdateVariant() {}

func (v SessionUpdateToolCall) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateToolCallSessionUpdate, v)}
}

const SessionUpdateToolCallUpdateSessionUpdate = "tool_call_update"

type SessionUpdateToolCallUpdate struct {
	ToolCallUpdate
}

func (SessionUpdateToolCallUpdate) isSessionUpdateVariant() {}

func (v SessionUpdateToolCallUpdate) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateToolCallUpdateSessionUpdate, v)}
}

const SessionUpdatePlanSessionUpdate = "plan"

type SessionUpdatePlan struct {
	Plan
}

func (SessionUpdatePlan) isSessionUpdateVariant() {}

func (v SessionUpdatePlan) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdatePlanSessionUpdate, v)}
}

const SessionUpdateAvailableCommandsUpdateSessionUpdate = "available_commands_update"

type SessionUpdateAvailableCommandsUpdate struct {
	AvailableCommandsUpdate
}

func (SessionUpdateAvailableCommandsUpdate) isSessionUpdateVariant() {}

func (v SessionUpdateAvailableCommandsUpdate) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateAvailableCommandsUpdateSessionUpdate, v)}
}

const SessionUpdateCurrentModeUpdateSessionUpdate = "current_mode_update"

type SessionUpdateCurrentModeUpdate struct {
	CurrentModeUpdate
}

func (SessionUpdateCurrentModeUpdate) isSessionUpdateVariant() {}

func (v SessionUpdateCurrentModeUpdate) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateCurrentModeUpdateSessionUpdate, v)}
}

const SessionUpdateConfigOptionUpdateSessionUpdate = "config_option_update"

type SessionUpdateConfigOptionUpdate struct {
	ConfigOptionUpdate
}

func (SessionUpdateConfigOptionUpdate) isSessionUpdateVariant() {}

func (v SessionUpdateConfigOptionUpdate) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateConfigOptionUpdateSessionUpdate, v)}
}

const SessionUpdateSessionInfoUpdateSessionUpdate = "session_info_update"

type SessionUpdateSessionInfoUpdate struct {
	SessionInfoUpdate
}

func (SessionUpdateSessionInfoUpdate) isSessionUpdateVariant() {}

func (v SessionUpdateSessionInfoUpdate) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: marshalDiscriminatedUnion("sessionUpdate", SessionUpdateSessionInfoUpdateSessionUpdate, v)}
}

type UnknownSessionUpdate struct {
	Discriminator string
	Raw           json.RawMessage
}

func (UnknownSessionUpdate) isSessionUpdateVariant() {}

func (v UnknownSessionUpdate) SessionUpdate() SessionUpdate {
	return SessionUpdate{data: append(json.RawMessage(nil), v.Raw...)}
}

func (m SessionUpdate) Variant() SessionUpdateVariant {
	variant, err := DecodeSessionUpdate(m.Raw())
	if err != nil {
		return UnknownSessionUpdate{Raw: m.Raw()}
	}
	return variant
}

func DecodeSessionUpdate(data json.RawMessage) (SessionUpdateVariant, error) {
	var header struct {
		SessionUpdate string `json:"sessionUpdate"`
	}
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, err
	}
	switch header.SessionUpdate {
	case SessionUpdateUserMessageChunkSessionUpdate:
		var value SessionUpdateUserMessageChunk
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateAgentMessageChunkSessionUpdate:
		var value SessionUpdateAgentMessageChunk
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateAgentThoughtChunkSessionUpdate:
		var value SessionUpdateAgentThoughtChunk
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateToolCallSessionUpdate:
		var value SessionUpdateToolCall
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateToolCallUpdateSessionUpdate:
		var value SessionUpdateToolCallUpdate
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdatePlanSessionUpdate:
		var value SessionUpdatePlan
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateAvailableCommandsUpdateSessionUpdate:
		var value SessionUpdateAvailableCommandsUpdate
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateCurrentModeUpdateSessionUpdate:
		var value SessionUpdateCurrentModeUpdate
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateConfigOptionUpdateSessionUpdate:
		var value SessionUpdateConfigOptionUpdate
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case SessionUpdateSessionInfoUpdateSessionUpdate:
		var value SessionUpdateSessionInfoUpdate
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	default:
		return UnknownSessionUpdate{Discriminator: header.SessionUpdate, Raw: append(json.RawMessage(nil), data...)}, nil
	}
}

const SetSessionConfigOptionRequestMethod = "session/set_config_option"

type SetSessionConfigOptionRequest struct {
	Meta      map[string]any       `json:"_meta,omitempty"`
	ConfigID  SessionConfigID      `json:"configId"`
	SessionID SessionID            `json:"sessionId"`
	Value     SessionConfigValueID `json:"value"`
}

const SetSessionConfigOptionResponseMethod = "session/set_config_option"

type SetSessionConfigOptionResponse struct {
	Meta          map[string]any        `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption `json:"configOptions"`
}

const SetSessionModeRequestMethod = "session/set_mode"

type SetSessionModeRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	ModeID    SessionModeID  `json:"modeId"`
	SessionID SessionID      `json:"sessionId"`
}

const SetSessionModeResponseMethod = "session/set_mode"

type SetSessionModeResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}

type StopReason string

const (
	StopReasonEndTurn         StopReason = "end_turn"
	StopReasonMaxTokens       StopReason = "max_tokens"
	StopReasonMaxTurnRequests StopReason = "max_turn_requests"
	StopReasonRefusal         StopReason = "refusal"
	StopReasonCancelled       StopReason = "cancelled"
)

type Terminal struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	TerminalID string         `json:"terminalId"`
}

type TerminalExitStatus struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	ExitCode *uint32        `json:"exitCode,omitempty"`
	Signal   *string        `json:"signal,omitempty"`
}

const TerminalOutputRequestMethod = "terminal/output"

type TerminalOutputRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

const TerminalOutputResponseMethod = "terminal/output"

type TerminalOutputResponse struct {
	Meta       map[string]any      `json:"_meta,omitempty"`
	ExitStatus *TerminalExitStatus `json:"exitStatus,omitempty"`
	Output     string              `json:"output"`
	Truncated  bool                `json:"truncated"`
}

type TextContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`
	Annotations *Annotations   `json:"annotations,omitempty"`
	Text        string         `json:"text"`
}

type TextResourceContents struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	MimeType *string        `json:"mimeType,omitempty"`
	Text     string         `json:"text"`
	URI      string         `json:"uri"`
}

type ToolCall struct {
	Meta       map[string]any     `json:"_meta,omitempty"`
	Content    []ToolCallContent  `json:"content,omitempty"`
	Kind       ToolKind           `json:"kind,omitempty"`
	Locations  []ToolCallLocation `json:"locations,omitempty"`
	RawInput   json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage    `json:"rawOutput,omitempty"`
	Status     ToolCallStatus     `json:"status,omitempty"`
	Title      string             `json:"title"`
	ToolCallID ToolCallID         `json:"toolCallId"`
}

type ToolCallContent struct {
	data json.RawMessage
}

func NewToolCallContentRaw(data json.RawMessage) ToolCallContent {
	return ToolCallContent{data: append(json.RawMessage(nil), data...)}
}

func (m *ToolCallContent) UnmarshalJSON(data []byte) error {
	m.data = append(m.data[:0], data...)
	return nil
}

func (m ToolCallContent) MarshalJSON() ([]byte, error) {
	if len(m.data) == 0 {
		return []byte("null"), nil
	}
	return m.data, nil
}

func (m ToolCallContent) Raw() json.RawMessage {
	return append(json.RawMessage(nil), m.data...)
}

type ToolCallContentVariant interface {
	isToolCallContentVariant()
	ToolCallContent() ToolCallContent
}

const ToolCallContentContentType = "content"

type ToolCallContentContent struct {
	Content
}

func (ToolCallContentContent) isToolCallContentVariant() {}

func (v ToolCallContentContent) ToolCallContent() ToolCallContent {
	return ToolCallContent{data: marshalDiscriminatedUnion("type", ToolCallContentContentType, v)}
}

const ToolCallContentDiffType = "diff"

type ToolCallContentDiff struct {
	Diff
}

func (ToolCallContentDiff) isToolCallContentVariant() {}

func (v ToolCallContentDiff) ToolCallContent() ToolCallContent {
	return ToolCallContent{data: marshalDiscriminatedUnion("type", ToolCallContentDiffType, v)}
}

const ToolCallContentTerminalType = "terminal"

type ToolCallContentTerminal struct {
	Terminal
}

func (ToolCallContentTerminal) isToolCallContentVariant() {}

func (v ToolCallContentTerminal) ToolCallContent() ToolCallContent {
	return ToolCallContent{data: marshalDiscriminatedUnion("type", ToolCallContentTerminalType, v)}
}

type UnknownToolCallContent struct {
	Discriminator string
	Raw           json.RawMessage
}

func (UnknownToolCallContent) isToolCallContentVariant() {}

func (v UnknownToolCallContent) ToolCallContent() ToolCallContent {
	return ToolCallContent{data: append(json.RawMessage(nil), v.Raw...)}
}

func (m ToolCallContent) Variant() ToolCallContentVariant {
	variant, err := DecodeToolCallContent(m.Raw())
	if err != nil {
		return UnknownToolCallContent{Raw: m.Raw()}
	}
	return variant
}

func DecodeToolCallContent(data json.RawMessage) (ToolCallContentVariant, error) {
	var header struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &header); err != nil {
		return nil, err
	}
	switch header.Type {
	case ToolCallContentContentType:
		var value ToolCallContentContent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case ToolCallContentDiffType:
		var value ToolCallContentDiff
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	case ToolCallContentTerminalType:
		var value ToolCallContentTerminal
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return value, nil
	default:
		return UnknownToolCallContent{Discriminator: header.Type, Raw: append(json.RawMessage(nil), data...)}, nil
	}
}

type ToolCallID string

type ToolCallLocation struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Line *uint32        `json:"line,omitempty"`
	Path string         `json:"path"`
}

type ToolCallStatus string

const (
	ToolCallStatusPending    ToolCallStatus = "pending"
	ToolCallStatusInProgress ToolCallStatus = "in_progress"
	ToolCallStatusCompleted  ToolCallStatus = "completed"
	ToolCallStatusFailed     ToolCallStatus = "failed"
)

type ToolCallUpdate struct {
	Meta       map[string]any     `json:"_meta,omitempty"`
	Content    []ToolCallContent  `json:"content,omitempty"`
	Kind       *ToolKind          `json:"kind,omitempty"`
	Locations  []ToolCallLocation `json:"locations,omitempty"`
	RawInput   json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *ToolCallStatus    `json:"status,omitempty"`
	Title      *string            `json:"title,omitempty"`
	ToolCallID ToolCallID         `json:"toolCallId"`
}

type ToolKind string

const (
	ToolKindRead       ToolKind = "read"
	ToolKindEdit       ToolKind = "edit"
	ToolKindDelete     ToolKind = "delete"
	ToolKindMove       ToolKind = "move"
	ToolKindSearch     ToolKind = "search"
	ToolKindExecute    ToolKind = "execute"
	ToolKindThink      ToolKind = "think"
	ToolKindFetch      ToolKind = "fetch"
	ToolKindSwitchMode ToolKind = "switch_mode"
	ToolKindOther      ToolKind = "other"
)

type UnstructuredCommandInput struct {
	Meta map[string]any `json:"_meta,omitempty"`
	Hint string         `json:"hint"`
}

const WaitForTerminalExitRequestMethod = "terminal/wait_for_exit"

type WaitForTerminalExitRequest struct {
	Meta       map[string]any `json:"_meta,omitempty"`
	SessionID  SessionID      `json:"sessionId"`
	TerminalID string         `json:"terminalId"`
}

const WaitForTerminalExitResponseMethod = "terminal/wait_for_exit"

type WaitForTerminalExitResponse struct {
	Meta     map[string]any `json:"_meta,omitempty"`
	ExitCode *uint32        `json:"exitCode,omitempty"`
	Signal   *string        `json:"signal,omitempty"`
}

const WriteTextFileRequestMethod = "fs/write_text_file"

type WriteTextFileRequest struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Content   string         `json:"content"`
	Path      string         `json:"path"`
	SessionID SessionID      `json:"sessionId"`
}

const WriteTextFileResponseMethod = "fs/write_text_file"

type WriteTextFileResponse struct {
	Meta map[string]any `json:"_meta,omitempty"`
}
