// Package api contains the public Discobot server API contract and client.
//
// The server's current handler/model types mostly live under server/internal,
// which keeps them unavailable to external consumers such as ui-go. This package
// is the public boundary we can grow into a shared contract for both server
// handlers and Go clients.
package api

import (
	"encoding/json"
	"time"
)

// ErrorResponse is the standard JSON error shape returned by the server.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse is returned by GET /health.
type HealthResponse struct {
	Status string `json:"status"`
}

// ServerConfig is the public server configuration returned to UI clients.
type ServerConfig struct {
	SSHPort       int    `json:"ssh_port"`
	HTTPPort      int    `json:"http_port"`
	HTTPSPort     int    `json:"https_port,omitempty"`
	HTTPSTLSMode  string `json:"https_tls_mode,omitempty"`
	PublicBaseURL string `json:"public_base_url"`
}

// Project is the API representation of a Discobot project.
type Project struct {
	ID                       string    `json:"id"`
	Name                     string    `json:"name"`
	Slug                     string    `json:"slug"`
	DefaultSandboxProviderID string    `json:"defaultSandboxProviderId,omitempty"`
	VZMemoryMB               *int      `json:"vz_memory_mb,omitempty"`
	VZDataDiskGB             *int      `json:"vz_data_disk_gb,omitempty"`
	CreatedAt                time.Time `json:"created_at"`
	UpdatedAt                time.Time `json:"updated_at"`
}

// Workspace is the API representation of a project workspace.
type Workspace struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"projectId"`
	Path          string    `json:"path"`
	DisplayName   *string   `json:"displayName,omitempty"`
	SourceType    string    `json:"sourceType"`
	AutoGenerated bool      `json:"autoGenerated"`
	Status        string    `json:"status"`
	ErrorMessage  *string   `json:"errorMessage,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// Session is the API representation of a session.
type Session struct {
	ID                string    `json:"id"`
	ProjectID         string    `json:"projectId"`
	WorkspaceID       string    `json:"workspaceId"`
	SandboxProviderID string    `json:"providerId,omitempty"`
	Name              string    `json:"name"`
	DisplayName       *string   `json:"displayName,omitempty"`
	Description       *string   `json:"description,omitempty"`
	SandboxStatus     string    `json:"sandboxStatus"`
	ThreadStatus      string    `json:"threadStatus,omitempty"`
	CommitStatus      string    `json:"commitStatus"`
	CommitOperation   *string   `json:"commitOperation,omitempty"`
	CommitError       *string   `json:"commitError,omitempty"`
	TargetRef         *string   `json:"targetRef,omitempty"`
	AppliedCommit     *string   `json:"appliedCommit,omitempty"`
	ErrorMessage      *string   `json:"errorMessage,omitempty"`
	WorkspacePath     *string   `json:"workspacePath,omitempty"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

// ModelInfo represents an AI model returned by GET /api/projects/{projectId}/models.
type ModelInfo struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Provider         string   `json:"provider"`
	Description      string   `json:"description,omitempty"`
	Reasoning        bool     `json:"reasoning,omitempty"`
	ReasoningLevels  []string `json:"reasoningLevels,omitempty"`
	DefaultReasoning string   `json:"defaultReasoning,omitempty"`
	ServiceTiers     []string `json:"serviceTiers,omitempty"`
}

// Thread is the API representation of a conversation thread.
type Thread struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	LastMessage     string          `json:"lastMessage,omitempty"`
	ErrorMessage    string          `json:"errorMessage,omitempty"`
	Model           string          `json:"model,omitempty"`
	Reasoning       string          `json:"reasoning,omitempty"`
	ServiceTier     string          `json:"serviceTier,omitempty"`
	State           string          `json:"state,omitempty"`
	PendingQuestion bool            `json:"pendingQuestion,omitempty"`
	ActiveCommand   string          `json:"activeCommand,omitempty"`
	Pending         bool            `json:"pending,omitempty"`
	PromptQueue     []QueuedPrompt  `json:"promptQueue,omitempty"`
	ActivityStatus  *ThreadActivity `json:"activityStatus,omitempty"`
	Metadata        json.RawMessage `json:"metadata,omitempty"`
}

// QueuedPrompt is a queued prompt attached to a conversation thread.
type QueuedPrompt struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt,omitzero"`
	RunAfter  time.Time `json:"runAfter,omitzero"`
	Prompt    string    `json:"prompt"`
}

// ThreadActivity is sparse non-idle thread activity state.
type ThreadActivity struct {
	Status       string     `json:"status"`
	Reason       string     `json:"reason,omitempty"`
	CompletionID *string    `json:"completionId,omitempty"`
	QueueCount   int        `json:"queueCount,omitempty"`
	NextRunAfter *time.Time `json:"nextRunAfter,omitempty"`
	Message      string     `json:"message,omitempty"`
}

// ThreadsResponse contains the list of threads in a session.
type ThreadsResponse struct {
	Threads []Thread `json:"threads"`
}

// ModelsResponse contains the list of available models.
type ModelsResponse struct {
	Models []ModelInfo `json:"models"`
}

// ChatRequest represents the request body for the chat endpoint.
//
// It matches the AI SDK's DefaultChatTransport format. Each element is a
// single UIMessage encoded as JSON.
type ChatRequest struct {
	// Messages is optional for create-only requests. When omitted or empty, the
	// handler creates/validates the session and returns an immediate empty SSE completion.
	Messages []json.RawMessage `json:"messages"`
	// Trigger indicates the type of request, such as "submit-message" or "regenerate-message".
	Trigger string `json:"trigger,omitempty"`
	// WorkspaceID is optional for new sessions. If omitted, the server creates
	// a local workspace under Discobot's data directory.
	WorkspaceID string `json:"workspaceId,omitempty"`
	// ProviderID is optional for new sessions and selects a sandbox provider instance.
	ProviderID string `json:"providerId,omitempty"`
	// Model is optional for new sessions.
	Model string `json:"model,omitempty"`
	// Reasoning controls extended thinking. This is passed through as a string
	// reasoning level such as "auto", "low", "medium", "high", "xhigh",
	// "none", "default", or "" for model/provider default behavior.
	Reasoning string `json:"reasoning,omitempty"`
	// ServiceTier optionally selects a provider latency tier, such as "fast".
	ServiceTier string `json:"serviceTier,omitempty"`
	// RunAfter queues the prompt until the given RFC3339 timestamp, even if the thread is idle.
	RunAfter string `json:"runAfter,omitempty"`
}

// ChatResponse contains metadata for an initiated chat request.
type ChatResponse struct {
	WorkspaceID    string `json:"workspaceId"`
	SessionID      string `json:"sessionId"`
	ThreadID       string `json:"threadId"`
	SubmissionID   string `json:"submissionId,omitempty"`
	MessageID      string `json:"messageId,omitempty"`
	CompletionID   string `json:"completionId,omitempty"`
	Status         string `json:"status,omitempty"`
	QueuedPromptID string `json:"queuedPromptId,omitempty"`
}

// Suggestion represents an autocomplete suggestion.
type Suggestion struct {
	Value          string `json:"value"`
	Type           string `json:"type"`
	Valid          bool   `json:"valid"`
	Classification string `json:"classification,omitempty"`
}

// TerminalMessage represents a message sent over the terminal WebSocket.
type TerminalMessage struct {
	Type string          `json:"type"` // "input", "output", "resize", "error"
	Data json.RawMessage `json:"data,omitempty"`
}

// ResizeData contains terminal resize dimensions.
type ResizeData struct {
	Rows int `json:"rows"`
	Cols int `json:"cols"`
}

// StatusMessageLevel represents the severity level of a status message.
type StatusMessageLevel string

const (
	// StatusLevelWarn indicates a warning status message.
	StatusLevelWarn StatusMessageLevel = "warn"
	// StatusLevelError indicates an error status message.
	StatusLevelError StatusMessageLevel = "error"
)

// StatusMessage represents a system status check message.
type StatusMessage struct {
	ID      string             `json:"id"`
	Level   StatusMessageLevel `json:"level"`
	Title   string             `json:"title"`
	Message string             `json:"message"`
}

// StartupTask represents a startup task being tracked.
type StartupTask struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	State            string     `json:"state"`
	Progress         *int       `json:"progress,omitempty"`
	CurrentOperation string     `json:"currentOperation,omitempty"`
	BytesDownloaded  *int64     `json:"bytesDownloaded,omitempty"`
	TotalBytes       *int64     `json:"totalBytes,omitempty"`
	Error            string     `json:"error,omitempty"`
	StartedAt        *time.Time `json:"startedAt,omitempty"`
	CompletedAt      *time.Time `json:"completedAt,omitempty"`
}

// SystemStatusResponse represents the complete system status.
type SystemStatusResponse struct {
	OK           bool            `json:"ok"`
	Messages     []StatusMessage `json:"messages"`
	StartupTasks []*StartupTask  `json:"startupTasks,omitempty"`
}

// SupportInfoResponse contains diagnostic information for debugging and support.
type SupportInfoResponse struct {
	Version    string               `json:"version"`
	Runtime    RuntimeInfo          `json:"runtime"`
	Config     ConfigInfo           `json:"config"`
	ServerLog  string               `json:"server_log"`
	LogPath    string               `json:"log_path"`
	LogExists  bool                 `json:"log_exists"`
	SystemInfo SystemStatusResponse `json:"system_info"`
}

// RuntimeInfo contains Go runtime information.
type RuntimeInfo struct {
	OS           string `json:"os"`
	Arch         string `json:"arch"`
	GoVersion    string `json:"go_version"`
	NumCPU       int    `json:"num_cpu"`
	NumGoroutine int    `json:"num_goroutine"`
}

// ConfigInfo contains sanitized configuration information.
type ConfigInfo struct {
	Port               int      `json:"port"`
	HTTPSPort          int      `json:"https_port,omitempty"`
	HTTPSTLSMode       string   `json:"https_tls_mode,omitempty"`
	DatabaseDriver     string   `json:"database_driver"`
	AuthEnabled        bool     `json:"auth_enabled"`
	WorkspaceDir       string   `json:"workspace_dir"`
	SandboxImage       string   `json:"sandbox_image"`
	SandboxImageRemote string   `json:"sandbox_image_remote,omitempty"`
	DesktopMode        bool     `json:"desktop_mode"`
	DesktopRuntime     string   `json:"desktop_runtime,omitempty"`
	SSHEnabled         bool     `json:"ssh_enabled"`
	SSHPort            int      `json:"ssh_port"`
	DispatcherEnabled  bool     `json:"dispatcher_enabled"`
	AvailableProviders []string `json:"available_providers"`
	VZ                 *VZInfo  `json:"vz,omitempty"`
}

// VZInfo contains VZ-specific configuration and disk usage information.
type VZInfo struct {
	ImageRef     string             `json:"image_ref"`
	DataDir      string             `json:"data_dir"`
	CPUCount     int                `json:"cpu_count"`
	MemoryMB     int                `json:"memory_mb"`
	DataDiskGB   int                `json:"data_disk_gb"`
	DiskUsage    *DiskUsageInfo     `json:"disk_usage,omitempty"`
	DataDisks    []DataDiskFileInfo `json:"data_disks,omitempty"`
	KernelPath   string             `json:"kernel_path,omitempty"`
	InitrdPath   string             `json:"initrd_path,omitempty"`
	BaseDiskPath string             `json:"base_disk_path,omitempty"`
}

// DiskUsageInfo contains filesystem usage statistics.
type DiskUsageInfo struct {
	TotalBytes     uint64  `json:"total_bytes"`
	UsedBytes      uint64  `json:"used_bytes"`
	AvailableBytes uint64  `json:"available_bytes"`
	UsedPercent    float64 `json:"used_percent"`
}

// DataDiskFileInfo contains size information for a sparse data disk file.
type DataDiskFileInfo struct {
	Path          string `json:"path"`
	ApparentBytes uint64 `json:"apparent_bytes"`
	ActualBytes   uint64 `json:"actual_bytes"`
}

// RouteInfo describes a registered API route from GET /api/routes.
type RouteInfo struct {
	Method      string          `json:"method"`
	Path        string          `json:"path"`
	Group       string          `json:"group"`
	Description string          `json:"description"`
	Params      []RouteParam    `json:"params,omitempty"`
	Body        json.RawMessage `json:"body,omitempty"`
}

// RouteParam describes a path or query parameter for a registered route.
type RouteParam struct {
	Name     string `json:"name"`
	In       string `json:"in"`
	Required bool   `json:"required,omitempty"`
	Example  string `json:"example,omitempty"`
}
