packages:
  - ui

allowBuilds:
  "@sentry/cli": true
  electron-winstaller: true
  esbuild: true

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - electron
  - electron-winstaller
  - esbuild
  - sharp
