packages:
  - ui
  - vscode-lite/web

allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  electron-winstaller: true
  esbuild: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - electron
  - electron-winstaller
  - esbuild
  - sharp
