root = ".."
testdata_dir = "testdata"
tmp_dir = "ui-go/build"

[build]
  args_bin = []
  entrypoint = "./build/ui-go"
  cmd = "pnpm assets:build && pnpm generate && go build -gcflags=\"all=-N -l\" -o ./build/ui-go ./cmd/ui-go"
  delay = 1000
  exclude_dir = ["assets", "build", "vendor", "testdata", "node_modules", "static/files"]
  exclude_file = ["static/app.css"]
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "UI_GO_STATIC_DIR=./static ./build/ui-go"
  include_dir = ["ui-go/cmd", "ui-go/content", "ui-go/scripts", "ui-go/styles", "server/api"]
  include_ext = ["go", "templ", "temple", "tpl", "tmpl", "html", "css", "js", "json", "svg"]
  include_file = [".env"]
  kill_delay = "10m"
  log = "ui-go/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
