[Unit]
After=discboeing-sandbox-init.service discboeing-proxy.service
Requires=discboeing-sandbox-init.service
Wants=discboeing-proxy.service

[Service]
EnvironmentFile=/run/discboeing/container-env
EnvironmentFile=-/run/discboeing/proxy-env

# Override default ExecStart to add custom data-root and log level
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --data-root /.data/docker --log-level error
