// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package app

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TerminalPanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t@layer components {\n\t\t\t.terminal-panel {\n\t\t\t\tdisplay: flex;\n\t\t\t\tmin-height: 180px;\n\t\t\t\tmax-height: 280px;\n\t\t\t\tflex: 0 0 220px;\n\t\t\t\tflex-direction: column;\n\t\t\t\toverflow: hidden;\n\t\t\t\tbackground: color-mix(in srgb, var(--surface-card) 92%, black);\n\t\t\t}\n\n\t\t\t.terminal-panel__header {\n\t\t\t\tdisplay: flex;\n\t\t\t\theight: 34px;\n\t\t\t\talign-items: center;\n\t\t\t\tjustify-content: space-between;\n\t\t\t\tborder-bottom: 1px solid var(--border-subtle);\n\t\t\t\tpadding: 0 12px;\n\t\t\t\tcolor: var(--muted-foreground);\n\t\t\t\tfont-size: 12px;\n\t\t\t}\n\n\t\t\t.terminal-panel__title {\n\t\t\t\tdisplay: flex;\n\t\t\t\talign-items: center;\n\t\t\t\tgap: 7px;\n\t\t\t\tcolor: var(--foreground);\n\t\t\t\tfont-weight: 600;\n\t\t\t}\n\n\t\t\t.terminal-panel__body {\n\t\t\t\tmin-height: 0;\n\t\t\t\tflex: 1 1 0%;\n\t\t\t\toverflow: hidden;\n\t\t\t\tpadding: 14px;\n\t\t\t\tcolor: var(--muted-foreground);\n\t\t\t\tfont-family: var(--font-mono);\n\t\t\t\tfont-size: 12px;\n\t\t\t}\n\n\t\t\t.terminal-panel__prompt {\n\t\t\t\tcolor: var(--diff-add-line);\n\t\t\t}\n\t\t}\n\t</style><section class=\"ide-panel terminal-panel\" aria-label=\"Terminal\"><header class=\"terminal-panel__header\"><div class=\"terminal-panel__title\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = IconTerminal("icon-sm").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<span>Terminal</span></div><span>Placeholder</span></header><div class=\"terminal-panel__body\"><div><span class=\"terminal-panel__prompt\">discobot $</span> terminal placeholder</div><div>Interactive terminal output will appear here.</div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
